In [1]:
import os
import mdtraj as md
import numpy as np
import pandas as pd

In [2]:
atlas_data_path = '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/workspace/chengkaihui/code/DFOLDv2_Motion_Next/src/toolbox/processing_atlas/data_csv/atlas_merged_all.csv'
atlas_data = pd.read_csv(atlas_data_path)
atlas_root_path = '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip/'

In [3]:
atlas_data.head(2)

,name,seqres,release_date,msa_id,atlas_npz,embed_path,seq_len
0,1k5n_A,GSHSMRYFHTSVSRPGRGEPRFITVGYVDDTLFVRFDSDAASPREE...,2002/10/30,1k5n_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,276
1,5e3e_A,MIINEKYPYLSYLLRCYFNQDFEVLFGNADETLAAYKATETAEERL...,2015/11/25,5e3e_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,104

In [4]:
atlas_data['pdb_path'] = atlas_data['name'].apply(lambda x: f'{atlas_root_path}/{x}/{x}.pdb')
atlas_data.head(2)

,name,seqres,release_date,msa_id,atlas_npz,embed_path,seq_len,pdb_path
0,1k5n_A,GSHSMRYFHTSVSRPGRGEPRFITVGYVDDTLFVRFDSDAASPREE...,2002/10/30,1k5n_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,276,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...
1,5e3e_A,MIINEKYPYLSYLLRCYFNQDFEVLFGNADETLAAYKATETAEERL...,2015/11/25,5e3e_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,104,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...

In [5]:
def compute_secondary_structure_proportions(pdb_path):
    """
    Compute the proportions of alpha helices, beta sheets, and coils in the given PDB file.

    Args:
    pdb_path (str): Path to the PDB file.

    Returns:
    tuple: Proportions of alpha helices, beta sheets, and coils.
    """
    traj = md.load(pdb_path)
    dssp = md.compute_dssp(traj)
    total_residues = dssp.shape[1]

    # Flatten the DSSP assignments and count occurrences
    dssp_flat = dssp.flatten()
    alpha_helix_count = np.sum(dssp_flat == 'H')
    beta_sheet_count = np.sum(dssp_flat == 'E')
    coil_count = np.sum((dssp_flat == 'C') | (dssp_flat == 'S') | (dssp_flat == 'T') | (dssp_flat == 'G') | (dssp_flat == 'B') | (dssp_flat == 'I'))

    # Calculate proportions
    alpha_helix_proportion = alpha_helix_count / len(dssp_flat)
    beta_sheet_proportion = beta_sheet_count / len(dssp_flat)
    coil_proportion = coil_count / len(dssp_flat)

    return alpha_helix_proportion, beta_sheet_proportion, coil_proportion

# compute_secondary_structure_proportions

In [6]:
atlas_data[['alpha_helix_proportion', 'beta_sheet_proportion', 'coil_proportion']] = atlas_data['pdb_path'].apply(
    lambda x: pd.Series(compute_secondary_structure_proportions(x))
)
atlas_data.head(2)

,name,seqres,release_date,msa_id,atlas_npz,embed_path,seq_len,pdb_path,alpha_helix_proportion,beta_sheet_proportion,coil_proportion
0,1k5n_A,GSHSMRYFHTSVSRPGRGEPRFITVGYVDDTLFVRFDSDAASPREE...,2002/10/30,1k5n_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,276,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.282609,0.384058,0.333333
1,5e3e_A,MIINEKYPYLSYLLRCYFNQDFEVLFGNADETLAAYKATETAEERL...,2015/11/25,5e3e_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,104,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.692308,0.000000,0.307692

In [11]:
df_sorted_desc = atlas_data.sort_values(by='seq_len', ascending=True)
df_sorted_desc

,name,seqres,release_date,msa_id,atlas_npz,embed_path,seq_len,pdb_path,alpha_helix_proportion,beta_sheet_proportion,coil_proportion
1131,4ue8_B,GPHMTKLIYERAFMKNLRGSPLSQTPPSNVPSCLLRGT,2015/2/25,4ue8_B,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,38,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.236842,0.000000,0.763158
540,3tvj_I,GSGEVTCEPGTTFKDKCNTCRCGSDGKSAVCTKLWCNQ,2012/4/25,3tvj_I,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,38,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.000000,0.315789,0.684211
1311,7lp1_A,VTQSFLPPGWEMRIAPNGRPFFIDHNTKTTTWEDPRLKF,2021/7/28,7lp1_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,39,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.000000,0.333333,0.666667
1093,2erl_A,DACEQAAIQCVESACESLCTEGEDRTGCYMYIYSNCPPYV,1996/7/11,2erl_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,40,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.625000,0.000000,0.375000
758,5w5c_A,GSNRRLQQTQAQVDEVVDIMRVNVDKVLERDQKLSELDDR,2017/8/23,5w5c_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,40,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.900000,0.000000,0.100000
...,...,...,...,...,...,...,...,...,...,...,...
129,1tg7_A,LLQKYVTWDEHSIFVNGERLMIFSGEVHPYRLPVASLYIDIFEKVK...,2004/11/2,1tg7_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,971,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.152420,0.318229,0.529351
373,1gte_D,MAPVLSKDVADIESILALNPRTQSHAALHSTLAKKLDKKHWKRNPD...,2002/4/11,1gte_D,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,1025,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.343415,0.163902,0.492683
154,4ayg_B,MGINGQQYYIDPTTGQPRKNFLLQNGNDWIYFDKDTGAGTNALKLQ...,2013/7/3,4ayg_B,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,1039,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.247353,0.210780,0.541867
999,2po4_A,ESTVTEELKEGIDAVYPSLVGTADSKAEGIKNYFKLSFTLPEEQKS...,2008/4/1,2po4_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,1104,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.569746,0.106884,0.323370
477,5vz0_A,LVPRGSHMKKLLVANRGEIAVRVFRACNELGLSTVAVYAREDEYSV...,2017/8/16,5vz0_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,1144,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.403846,0.204545,0.391608

In [ ]:
# tmp_df = df_sorted_desc[df_sorted_desc['beta_sheet_proportion'] == 0]
tmp_df = df_sorted_desc[(df_sorted_desc['beta_sheet_proportion'] != 0) & (df_sorted_desc['alpha_helix_proportion'] != 0)]
# tmp_df.iloc[300:360]

In [37]:
names_list = ['4ue8_B',	'6l34_A','5h6x_A',	'5eqz_A', '3tvj_I'	,'1ok0_A',	'3po8_A',	'1ouw_C' ,'2hba_A'	,'1ctf_A',	'7n0j_E',	'6bwq_A']
filtered_df = atlas_data[atlas_data['name'].isin(names_list)]
filtered_df

,name,seqres,release_date,msa_id,atlas_npz,embed_path,seq_len,pdb_path,alpha_helix_proportion,beta_sheet_proportion,coil_proportion
111,3po8_A,SAGTSVTLQLDDGSGRTYQLREGSNIIGRGQDAQFRLPDTGVSRRH...,2011/1/26,3po8_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,100,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.000000,0.480000,0.520000
163,1ouw_C,AVPMDTISGPWGNNGGNFWSFRPVNKINQIVISYGGGGNNPIALTF...,2003/11/11,1ouw_C,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,152,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.000000,0.611842,0.388158
266,1ctf_A,AAEEKTEFDVILKAAGANKVAVIKAVRGATGLGLKEAKDLVESAPA...,1987/1/15,1ctf_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,74,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.472973,0.243243,0.283784
332,5h6x_A,EIGFSPLLTAEEEIHYATLALKGDMEARKKMIESNLRLVVKIARRY...,2017/11/22,5h6x_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,100,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.740000,0.000000,0.260000
540,3tvj_I,GSGEVTCEPGTTFKDKCNTCRCGSDGKSAVCTKLWCNQ,2012/4/25,3tvj_I,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,38,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.000000,0.315789,0.684211
575,2hba_A,MKVIFLKDVKGMGKKGEIKNVADGYANNFLFKQGLAIEATPANLKA...,2007/5/29,2hba_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,52,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.326923,0.230769,0.442308
899,5eqz_A,MAHHHHHHYVEEKKEIDSLMEDVLALVNDSSGGKFKDYKDKINELK...,2015/12/9,5eqz_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,146,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.678082,0.000000,0.321918
1047,1ok0_A,DTTVSEPAPSCVTLYQSWRYSQADNGCAETVTVKVVYEDDTEGLCY...,2004/1/15,1ok0_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,74,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.000000,0.472973,0.527027
1131,4ue8_B,GPHMTKLIYERAFMKNLRGSPLSQTPPSNVPSCLLRGT,2015/2/25,4ue8_B,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,38,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.236842,0.000000,0.763158
1312,6l34_A,KRPMSAYMLWLNASREKIKSDHPGISITDLSKKAGEIWKGMSKEKK...,2020/10/14,6l34_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,68,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.867647,0.000000,0.132353
1328,7n0j_E,APQVITVSRFEVGKDKWAFNREEVMLTCRPGNALYVINPSTLVQYP...,2022/3/9,7n0j_E,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,101,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.336634,0.247525,0.415842
1355,6bwq_A,TADAVLMIEANLDDQTGEGLGYVMNQLLTAGAYDVFFTPIQMKKDR...,2018/6/20,6bwq_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,149,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.328859,0.409396,0.261745

In [38]:
filtered_df = filtered_df.sort_values(by='seq_len', ascending=True)
filtered_df

,name,seqres,release_date,msa_id,atlas_npz,embed_path,seq_len,pdb_path,alpha_helix_proportion,beta_sheet_proportion,coil_proportion
540,3tvj_I,GSGEVTCEPGTTFKDKCNTCRCGSDGKSAVCTKLWCNQ,2012/4/25,3tvj_I,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,38,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.000000,0.315789,0.684211
1131,4ue8_B,GPHMTKLIYERAFMKNLRGSPLSQTPPSNVPSCLLRGT,2015/2/25,4ue8_B,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,38,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.236842,0.000000,0.763158
575,2hba_A,MKVIFLKDVKGMGKKGEIKNVADGYANNFLFKQGLAIEATPANLKA...,2007/5/29,2hba_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,52,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.326923,0.230769,0.442308
1312,6l34_A,KRPMSAYMLWLNASREKIKSDHPGISITDLSKKAGEIWKGMSKEKK...,2020/10/14,6l34_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,68,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.867647,0.000000,0.132353
266,1ctf_A,AAEEKTEFDVILKAAGANKVAVIKAVRGATGLGLKEAKDLVESAPA...,1987/1/15,1ctf_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,74,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.472973,0.243243,0.283784
1047,1ok0_A,DTTVSEPAPSCVTLYQSWRYSQADNGCAETVTVKVVYEDDTEGLCY...,2004/1/15,1ok0_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,74,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.000000,0.472973,0.527027
111,3po8_A,SAGTSVTLQLDDGSGRTYQLREGSNIIGRGQDAQFRLPDTGVSRRH...,2011/1/26,3po8_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,100,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.000000,0.480000,0.520000
332,5h6x_A,EIGFSPLLTAEEEIHYATLALKGDMEARKKMIESNLRLVVKIARRY...,2017/11/22,5h6x_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,100,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.740000,0.000000,0.260000
1328,7n0j_E,APQVITVSRFEVGKDKWAFNREEVMLTCRPGNALYVINPSTLVQYP...,2022/3/9,7n0j_E,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,101,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.336634,0.247525,0.415842
899,5eqz_A,MAHHHHHHYVEEKKEIDSLMEDVLALVNDSSGGKFKDYKDKINELK...,2015/12/9,5eqz_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,146,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.678082,0.000000,0.321918
1355,6bwq_A,TADAVLMIEANLDDQTGEGLGYVMNQLLTAGAYDVFFTPIQMKKDR...,2018/6/20,6bwq_A,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,149,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.328859,0.409396,0.261745
163,1ouw_C,AVPMDTISGPWGNNGGNFWSFRPVNKINQIVISYGGGGNNPIALTF...,2003/11/11,1ouw_C,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy...,152,/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/pub...,0.000000,0.611842,0.388158

In [39]:
filtered_df.to_csv('/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/workspace/chengkaihui/code/DFOLDv2_Motion_Next/debug_tool/4D_data/aaai_paper_data.csv')

In [43]:
save_dir = '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/workspace/chengkaihui/code/DFOLDv2_Motion_Next/debug_tool/4D_data'
list(filtered_df['pdb_path'])

['/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//3tvj_I/3tvj_I.pdb',
 '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//4ue8_B/4ue8_B.pdb',
 '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//2hba_A/2hba_A.pdb',
 '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//6l34_A/6l34_A.pdb',
 '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//1ctf_A/1ctf_A.pdb',
 '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//1ok0_A/1ok0_A.pdb',
 '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//3po8_A/3po8_A.pdb',
 '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//5h6x_A/5h6x_A.pdb',
 '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//7n0j_E/7n0j_E.pdb',
 '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//5eqz_A/5eqz_A.pdb',
 '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//6bwq_A/6bwq_A.pdb',
 '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/protein/datasets/atlas/atlas_unzip//1ouw_C/1ouw_C.pdb']

In [44]:
import shutil

for SourceDataPath in list(filtered_df['pdb_path']):
    shutil.copy(SourceDataPath,os.path.join(save_dir,os.path.basename(SourceDataPath)))